services:
  chroma:
    image: 'chromadb/chroma:latest'
    ports:
      - '8000'
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  qdrant:
    image: 'qdrant/qdrant:latest'
    ports:
      - '6334'
